:sparkles: Add ontology lamin upload
laminlabs/bionty-base pull request #292
Opened 2023-03-29 20:06 UTC by Zethson

Fixes #270 

Remaining TODOs

- [ ] Test thoroughly
- [ ] Connect everything with the CI
- [ ] Add script to add the new paths to the versions.yml as a PR or so

2023-04-04 15:56 UTC, Zethson commented
The current version creates

```
version: 0.1.0
Species:
  ensembl:
    versions:
      release-108:
      - s3://lukas-bionty-test/OGYoEt4UwMCBisCxW7Uq
      - ''
    name: Ensembl
    website: https://www.ensembl.org/index.html
Gene:
  ensembl:
    versions:
      release-108:
      - https://ftp.ensembl.org/pub/release-108/mysql/
      - ''
      release-107:
      - https://ftp.ensembl.org/pub/release-107/mysql/
      - ''
    name: Ensembl
    website: https://www.ensembl.org/index.html
Protein:
  uniprot:
    versions:
      2022-04:
      - https://ftp.uniprot.org/pub/databases/uniprot/current_release/
      - ''
      2022-03:
      - https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_03/
      - ''
    name: Uniprot
    website: https://www.uniprot.org/
CellMarker:
  cellmarker:
    versions:
      '2.0':
      - http://bio-bigdata.hrbmu.edu.cn/CellMarker/CellMarker_download_files/file/Cell_marker_All.xlsx
      - ''
    name: CellMarker
    website: http://bio-bigdata.hrbmu.edu.cn/CellMarker/
CellLine:
  clo:
    versions:
      '2022-03-21':
      - s3://lukas-bionty-test/0hJUeKDLwaBIi3gQB4yD
      - ea58a1010b7e745702a8397a526b3a33
    name: Cell Line Ontology
    website: https://bioportal.bioontology.org/ontologies/CLO
CellType:
  cl:
    versions:
      '2023-02-15':
      - http://purl.obolibrary.org/obo/cl/releases/2023-02-15/cl-base.owl
      - 9331a6a029cb1863bd0584ab41508df7
      '2022-08-16':
      - s3://lukas-bionty-test/TD075dpP4D0xRBmwLddU
      - d0655766574e63f3fe5ed56d3c030880
    name: Cell Ontology
    website: https://obophenotype.github.io/cell-ontology/
  ca:
    versions:
      '2022-12-16':
      - https://www.ebi.ac.uk/ols/ontologies/hcao/download
      - 98ba0d340bd1b34659e8a0bdd9535127
    name: Human Cell Atlas Ontology
    website: https://github.com/HumanCellAtlas/ontology
Tissue:
  uberon:
    versions:
      '2023-02-14':
      - s3://lukas-bionty-test/gniTOWbervGMCm2ggdxI
      - 3f94e22fae4cdde88a555c5cd59c47da
      '2022-08-19':
      - http://purl.obolibrary.org/obo/uberon/releases/2022-08-19/uberon.owl
      - c7c958a1ee48fdce146f2c1763eed27e
    name: Uberon multi-species anatomy ontology
    website: http://obophenotype.github.io/uberon/
Disease:
  mondo:
    versions:
      '2023-02-06':
      - s3://lukas-bionty-test/J1j6s94asalfhOmoYFmk
      - 2b7d479d4bd02a94eab47d1c9e64c5db
      '2022-10-11':
      - http://purl.obolibrary.org/obo/mondo/releases/2022-10-11/mondo.owl
      - 04b808d05c2c2e81430b20a0e87552bb
    name: Mondo Disease Ontology
    website: https://mondo.monarchinitiative.org/
  doid:
    versions:
      '2023-01-30':
      - http://purl.obolibrary.org/obo/doid/releases/2023-01-30/doid.obo
      - 9f0c92ad2896dda82195e9226a06dc36
    name: Human Disease Ontology
    website: https://disease-ontology.org/
Readout:
  efo:
    versions:
      3.48.0:
      - http://www.ebi.ac.uk/efo/releases/v3.48.0/efo.owl
      - 3367e9a9ae3dee9113024e5108c49091
    name: The Experimental Factor Ontology
    website: https://bioportal.bioontology.org/ontologies/EFO
Phenotype:
  hp:
    versions:
      '2023-01-27':
      - s3://lukas-bionty-test/3mNyWmp5KII917J8MBzO
      - ceeb3ada771908deef620d74cd8e6b0f
    name: Human Phenotype Ontology
    website: https://hpo.jax.org/
Pathway:
  pw:
    versions:
      7-74:
      - s3://lukas-bionty-test/II07y7XuK0IfhXe5PZM2
      - a6df86616149dcdfe08fe16c900cba85
    name: Pathway Ontology
    website: https://www.ebi.ac.uk/ols/ontologies/pw
```

2023-04-11 15:28 UTC, sunnyosun requested changes

2023-04-11 15:28 UTC, sunnyosun commented on README.md
> +# Bionty: Curate metadata using ontologies
I think I like the previous version better, as it specifies managing and versioning.

2023-04-11 15:28 UTC, sunnyosun commented on bionty/_entity.py
> +        if url.startswith("s3"):
Could we do `.startswith("s3://bionty-assets/")` here to be safe? Just in case other urls are also S3 urls.

2023-04-11 15:28 UTC, sunnyosun commented on bionty/versions/versions.yaml
> +      "2022-03-21":
Is the "" here necessary? Could you convert the date to str after reading it? I fear it's a bit much if users need to put that and they can very likely forget.

2023-04-11 15:28 UTC, sunnyosun commented on bionty/versions/versions.yaml
> +      7-74:
Also here, could we stick with "7.74" if that's the version label from the source?

2023-04-11 15:28 UTC, sunnyosun commented on noxfile.py
> +        session.run(
Why do we need this instance?

2023-04-11 15:28 UTC, sunnyosun commented on scripts/upload_new_ontologies.py
> +                    ontology_ln_file = ln.File(latest_path, source=run)
I think you should switch to `ln.File(latest_path, key=..., source=run)` so that the s3 filenames are the same as the local filenames. Alex just added it in the latest lamindb so that one can use semantics for the uploaded files. Then we don't even need the s3 paths in the versions.yaml file anymore as you can reconstruct it based on filenames.

See here for an example: https://github.com/laminlabs/laminci/blob/5e1634a68c9b87324ae4bc3b9f0ec9734ae640ed/laminci/_artifacts.py#L41-L46

2023-04-11 16:04 UTC, Zethson commented on README.md
> +# Bionty: Curate metadata using ontologies
This was Alex :)

https://github.com/laminlabs/bionty/commit/8d74b9d29ce025d11c0e8741e9f9ba989300a243

2023-04-12 13:25 UTC, Zethson commented on noxfile.py
> +        session.run(
Also a change by Alex :)

2023-04-12 13:34 UTC, Zethson commented on bionty/versions/versions.yaml
> +      "2022-03-21":
https://github.com/laminlabs/bionty/blob/feature/lamin_ontology_upload/bionty/dev/_io.py#L10

Already happening here.

2023-04-13 13:21 UTC, Zethson commented
lnschema-bionty fails with 

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/dev/_setup_schema.py", line 97, in check_schema_version_and_import
    module = importlib.import_module(get_schema_module_name(schema_name))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lnschema_bionty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 383, in from_name
    return next(cls.discover(name=name))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/bin/lamin", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/__main__.py", line 103, in main
    result = _init_instance.init(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/_init_instance.py", line 139, in init
    persist_settings_load_schema(isettings)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/_init_instance.py", line 49, in persist_settings_load_schema
    load_schema(isettings)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/dev/_setup_schema.py", line 115, in load_schema
    module = check_schema_version_and_import(schema_name)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/lndb/dev/_setup_schema.py", line 101, in check_schema_version_and_import
    module_version = get_pip_version(get_schema_module_name(schema_name))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 877, in version
    return distribution(distribution_name).version
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 850, in distribution
    return Distribution.from_name(distribution_name)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 385, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for lnschema_bionty
```

2023-04-13 13:44 UTC, sunnyosun approved these changes
Let's merge this!

2023-04-13 14:42 UTC, merged